//
//  TaskTableViewCell.swift
//  MicroReminders
//
//  Created by Sasha Weiss on 5/14/16.
//  Copyright © 2016 Sasha Weiss. All rights reserved.
//

import UIKit

class TaskTableViewCell: UITableViewCell {

    
    @IBOutlet weak var TaskNameLabel: UILabel!
    @IBOutlet weak var mt1Label: UILabel!
    @IBOutlet weak var mt2Label: UILabel!
    @IBOutlet weak var mt3Label: UILabel!
    @IBOutlet weak var loc1Label: UILabel!
    @IBOutlet weak var loc2Label: UILabel!
    @IBOutlet weak var loc3Label: UILabel!
    @IBOutlet weak var currStep: UILabel!
    
    
    //******************************* autogenerated code
    
    override func awakeFromNib() {
        super.awakeFromNib()
        // Initialization code
    }

    override func setSelected(selected: Bool, animated: Bool) {
        super.setSelected(selected, animated: animated)

        // Configure the view for the selected state
    }

}
