prepopTasks = [{"task":"Wash dirty dishes in the sink","category":"Cleaning and tidying","subcategory":"Food"},
{"task":"Bring dirty dishes to the sink","category":"Cleaning and tidying","subcategory":"Food"},
{"task":"Put away clean dishes","category":"Cleaning and tidying","subcategory":"Food"},
{"task":"Put perishables in the fridge","category":"Cleaning and tidying","subcategory":"Food"},
{"task":"Put frozen food in the fridge","category":"Cleaning and tidying","subcategory":"Food"},
{"task":"Wipe the stovetop","category":"Cleaning and tidying","subcategory":"Food"},
{"task":"Wipe the counters","category":"Cleaning and tidying","subcategory":"Food"},
{"task":"Put dirty clothes in the laundry bin","category":"Cleaning and tidying","subcategory":"Laundry"},
{"task":"Fold some clothes","category":"Cleaning and tidying","subcategory":"Laundry"},
{"task":"Make my bed","category":"Cleaning and tidying","subcategory":"Organization"},
{"task":"Put my shoes on the rack","category":"Cleaning and tidying","subcategory":"Organization"},
{"task":"Hang up my jacket","category":"Cleaning and tidying","subcategory":"Organization"},
{"task":"Hang up my keys","category":"Cleaning and tidying","subcategory":"Organization"},
{"task":"Take out the trash","category":"Cleaning and tidying","subcategory":"Trash"},
{"task":"Take out the recycling","category":"Cleaning and tidying","subcategory":"Trash"},
{"task":"Take vitamins","category":"Health and wellness","subcategory":"Consumption"},
{"task":"Drink a glass of water","category":"Health and wellness","subcategory":"Consumption"},
{"task":"Fill a water bottle","category":"Health and wellness","subcategory":"Consumption"},
{"task":"Grab a snack","category":"Health and wellness","subcategory":"Consumption"},
{"task":"Put gym clothes in my bag","category":"Health and wellness","subcategory":"Activity"},
{"task":"Do a yoga pose","category":"Health and wellness","subcategory":"Activity"},
{"task":"Lock the door","category":"Home maintenance","subcategory":"Checking"},
{"task":"Pick up the mail","category":"Home maintenance","subcategory":"Checking"},
{"task":"Turn off the light","category":"Home maintenance","subcategory":"Checking"},
{"task":"Pack a meal","category":"Home maintenance","subcategory":"Preparation"},
{"task":"Pack my bag","category":"Home maintenance","subcategory":"Preparation"},
{"task":"Change my bath towel","category":"Home maintenance","subcategory":"Replacement"},
{"task":"Change the toilet paper roll","category":"Home maintenance","subcategory":"Replacement"},
{"task":"Fill the Brita filter","category":"Home maintenance","subcategory":"Replacement"},
{"task":"Water my plants","category":"Home maintenance","subcategory":"Other"},
{"task":"Feed my pets","category":"Home maintenance","subcategory":"Other"},
{"task":"Put my phone on the charger","category":"Home maintenance","subcategory":"Preparation"}]
